apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "model-manager-server.fullname" . }}-http
  labels:
    {{- include "model-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - {{- if .Values.global.ingress.host }}
    host: {{ .Values.global.ingress.host }}
    {{- end }}
    http:
      paths:
      - path: /v1/models
        pathType: Prefix
        backend:
          service:
            name: {{ include "model-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}

---

{{- if .Values.global.workerServiceIngress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "model-manager-server.fullname" . }}-worker-service-grpc
  labels:
    {{- include "model-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.workerServiceIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - {{- if .Values.global.ingress.host }}
    host: {{ .Values.global.ingress.host }}
    {{- end }}
    http:
      paths:
      - path: /llmariner.models.server.v1.ModelsWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "model-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
{{- end -}}
